// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdDFR9OK_rqQ8zmYGHfwkiJX8ec_9iYmc',
    appId: '1:965746968148:web:9a75b29e3cb9b6e5d68fc1',
    messagingSenderId: '965746968148',
    projectId: 'flutter-test-f2551',
    authDomain: 'flutter-test-f2551.firebaseapp.com',
    storageBucket: 'flutter-test-f2551.appspot.com',
    measurementId: 'G-6XBW97EPT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJET4y--45X8k3GQAZfVqe4XeaHHZOIGU',
    appId: '1:965746968148:android:fe4c99cf10bab2dad68fc1',
    messagingSenderId: '965746968148',
    projectId: 'flutter-test-f2551',
    storageBucket: 'flutter-test-f2551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCxiFeP52u1KIn5qpI9nHmBiFmCneeVUA',
    appId: '1:965746968148:ios:6d982b96d778d146d68fc1',
    messagingSenderId: '965746968148',
    projectId: 'flutter-test-f2551',
    storageBucket: 'flutter-test-f2551.appspot.com',
    iosClientId: '965746968148-ukinfg4a5ilgucbt2va6lne6klcg1dap.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCxiFeP52u1KIn5qpI9nHmBiFmCneeVUA',
    appId: '1:965746968148:ios:6d982b96d778d146d68fc1',
    messagingSenderId: '965746968148',
    projectId: 'flutter-test-f2551',
    storageBucket: 'flutter-test-f2551.appspot.com',
    iosClientId: '965746968148-ukinfg4a5ilgucbt2va6lne6klcg1dap.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondFirebase',
  );
}
